### ISSUE TITLE
Disable auto update of value

### ISSUE THREAD

**Issue by divanshujain** [marcocesarato/react-native-input-spinner#10]
Is there a way that we can manually update the value of the spinner and disable the auto addition or subtraction ?

Our use case includes a popup when we tap "+" or "-" in which you can cancel the update. However, the spinner still updates the value.

Any help regarding the same would be appreciated.

**Comment by OneHatRepo** [comment]
Same issue here. Canceling the change doesn't allow the component to re-render with the appropriate value, since the internal state has changed, but the props.value has not.

The solution is to change line 58 in index.js from:
`		if (this.props.value !== prevProps.value) {`
to:
`		if (this.props.value !== this.state.value) {`

**Comment by marcocesarato** [comment]
Fixed on release v1.3.3

**Comment by OneHatRepo** [comment]
@marcocesarato If I'm understanding you correctly, I don't think that will work with my use case. 

I've got a FlatList with many rows, each having an InputSpinner. The data comes from a Redux store.
The updateCart() handler method doesn't return anything, but rather dispatches an action to Redux. It _can't_ return anything because this happens in response to user input in an Alert. i.e. The updateCart() method has finished execution _before_ the user has decided whether or not to cancel the change. Alert does not have async capability, so we can't wait for user input before returning the result.

```
const updateCart = (item, qty) => {
	function doIt() {
		actions.updateCartItem(item, qty); // dispatch action to Redux
	}
	if (qty > 0) {
		doIt();
	} else {
		Alert.alert(
			'Delete item from cart?',
			null,
			[
				{ text: 'Cancel', style: 'cancel', },
				{ text: 'Delete', style: 'destructive', onPress: doIt, },
			]
		);
	}
};

// Later, within the row of the FlatList...
(item) => <InputSpinner
		value={item.qty}
		onChange={qty => updateCart(item, qty)}
	/>
```

We need to have a way for the InputSpinner to be a controlled component, so it always reflects the value of the "value" prop whenever it's rendered.

**Comment by marcocesarato** [comment]
This already happens. I did a test (you can find in the Example folder) with a FlatList and updating the value of the state, using a button and it change so that I don't find any issues related the managed data value, using props, on the component.

**Comment by OneHatRepo** [comment]
@marcocesarato, 1.3.6 is still broken for my use case. Please try this: 

```
import React, { useState, } from 'react';
import {
	Alert,
} from 'react-native';
import InputSpinner from 'react-native-input-spinner';

export default function Tester() {
	const [qty, setQty] = useState(1),
		onChange = (value) => {
			Alert.alert(
				'Are you sure?',
				null,
				[
					{ text: 'Cancel', style: 'cancel', },
					{ text: 'Yes', style: 'destructive', onPress: () => {
						setQty(value);
					}, },
				]
			);
		};
	return <InputSpinner
			value={qty}
			onChange={onChange}
		/>;
}
```

- Press either the "-" or "+" button, which brings up an Alert, asking the user to verify the change. 
- Cancel the Alert, signifying the user doesn't want to change the value.
- The InputSpinner is now receiving qty of 1 from props, but it shows either 0 or 2.

Within `componentDidUpdate`, the InputSpinner needs to verify that `this.props.value` matches `this.state.value`, and if they don't match, then the internal state needs to conform to `this.props.value`.

**Comment by marcocesarato** [comment]
@OneHatRepo 
Just try like this:
```javascript
import React, { useState, } from 'react';
import {Alert} from "react-native";
import InputSpinner from './index';

export default function Tester() {
	const [qty, setQty] = useState(1);
	const onChange = (value) => {
		Alert.alert(
			'Are you sure?',
			null,
			[
				{ text: 'Cancel', style: 'cancel', },
				{ text: 'Yes', style: 'destructive', onPress: () => {
						setQty(value);
					}, },
			]
		);
		return false;
	};
	return <InputSpinner
		width={300}
		value={qty}
		onChange={onChange}
	/>;
}
```

**Comment by OneHatRepo** [comment]
OK that worked. Thank you.
